version: "3.8"

services:
  db:
    container_name: postgre_test
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: soldev2023_test_env
      POSTGRES_PASSWORD: test_env_pass
      POSTGRES_DB: test_db

  app:
    container_name: server_test
    build: ./src
    environment:
    - ENV=test
    command: bash -c "sleep 2 && cd .. && python -m pytest src/tests"

    depends_on:
      - db

    
    restart: "no"

