version: "3.8"

services:

  app:
    container_name: server_prod
    build: ./src
    environment:
    - ENV=prod

    command: bash -c "sleep 2 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --no-server-header"
    ports:
    - 8000:8000
    restart: always
    depends_on:
      - nginx
  

  nginx:
    container_name: nginx_server
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    # volumes:
    #   - ./data/nginx_data/log/nginx:/var/log/nginx