version: "3.8"

services:

  app:

    container_name: server_prod
    build: ./src
    environment:
      POSTGRE_PASS: ${POSTGRE_PASS}
      POSTGRE_USER: ${POSTGRE_USER}
      POSTGRE_HOST: ${POSTGRE_HOST}
      ENV: prod

    command: bash -c "sleep 2 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --no-server-header"
    ports:
    - 8000:8000
    restart: always

  nginx:
    container_name: nginx_server
    build: ./nginx
    ports:
      - 80:80
      - 443:443
