name: validation_back

on:
  push:
    branches: [master]
    paths:
      - back/**
  pull_request:
    branches: [master]



jobs:
  test:
    # if: github.ref == 'refs/heads/master'
    name: Server test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build containers
        run: docker-compose -f docker-compose.test.yml build

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml up --exit-code-from app
