name: Test

on:
  pull_request:
    branches: [master]



jobs:
  testBack:
    name: Server test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build containers
        run: docker-compose -f docker-compose.test.yml build

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml up --exit-code-from app


  testFront:
    needs: testBack
    name: Front test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./front

    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      
      - name: Intall dependecies
        run: npm install

      - name: Test
        run: npm test


